### ISSUE TITLE
Hello, does your RWT-SLAM combine loftr with orb-slam2?

### ISSUE THREAD

**Issue by xu-no1** [TonyPhh/RWT-SLAM#3]
Hello, does your RWT-SLAM combine loftr with orb-slam2?

**Comment by jf99** [comment]
According to the [paper](https://arxiv.org/pdf/2207.03539.pdf), yes. In section III it is stated:

> The generation of keypoint descriptors from the detector-free network LoFTR [14] is introduced in part A. Then the reformation of ORB-SLAM2 [4] to make it adaptive to the new feature points is described in part B.

**Comment by xu-no1** [comment]
Thank you for your answer and I look forward to making your code open source
